hydra:
  run:
    dir: logs/${network.name}_${run.distrib}_${now:%Y-%m-%d_%H-%M-%S}

network:
  name: flow++
  layers: 16

train:
  steps: 1800
  samples: 1024

optimizer:
  name: adam
  lr: 4.0e-4
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.0
  decay_steps: 300
  decay_ratio: 0.5

run:
  gpu: 0
  debug: False
  distrib: ggd
  ckpt_path: null
  output: outputs
  display: 1

defaults:
  - network: flow++
